homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 32.985832
  longitude: -96.785329
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 196
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: US/Central
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  base_url: https://ickespad.duckdns.org:8123
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# zone:
#   name: Work
#   latitude: 32.971629
#   longitude: -96.822634

# Track the sun
sun:

# Weather prediction
sensor:
  - platform: yr

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

# Nest
nest:
  client_id: !secret nest_clientIdToken 
  client_secret: !secret nest_secretToken

# Insteon Hub
insteon_local:
  host: 192.168.1.74
  username: !secret insteon_user
  password: !secret insteon_pass

# TP Link aka Kasa App devices below
switch 1:
  - platform: tplink
    host: 192.168.1.103
    name: Hallway Sound Machine

switch 2:
  - platform: tplink
    host: 192.168.1.98
    name: Nursery Lamp

light 1:
  - platform: tplink
    host: 192.168.1.67
    name: Office Light
    
light 2:
  - platform: tplink
    host: 192.168.1.102
    name: Living Room Lamp 1

light 3:
  - platform: tplink
    host: 192.168.1.71
    name: Living Room Lamp 2

# Rainmachine integration test change
rainmachine:
  ip_address: 192.168.1.86
  password: !secret rainmachine_token

# Garage Door status
cover:
  - platform: myq
    username: james.ickes@gmail.com
    password: !secret garagedoor_password
    type: chamberlain

# Adding Configuration to sidebar
panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://hassio.local:3218

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
